// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQYKd2dny3RVhqPhrj6JGTLBJy4inXTXA',
    appId: '1:536967123123:android:69e72a55530645de31e0c6',
    messagingSenderId: '536967123123',
    projectId: 'gdsc-nuces-khi',
    storageBucket: 'gdsc-nuces-khi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6swT3czNUv44fkpXLsEJUkiUO4gH3KLE',
    appId: '1:536967123123:ios:6edfd78fcc0a256331e0c6',
    messagingSenderId: '536967123123',
    projectId: 'gdsc-nuces-khi',
    storageBucket: 'gdsc-nuces-khi.appspot.com',
    androidClientId: '536967123123-orve32286g336msp5ug4qhdafkgc9rs5.apps.googleusercontent.com',
    iosClientId: '536967123123-lp9seq073oo2pjl935e2rjkkoqk45ttc.apps.googleusercontent.com',
    iosBundleId: 'com.nuces.gdscAdmin',
  );
}
